[build-system]
requires=["setuptools>=42.0","wheel"]
build-backend="setuptools.build_meta"

[tool.pytest.ini_options]
testpaths=[
    "test"
    ]

[too.mypy]
mypy_path="src"
ignore_missing_import=true